module Maze

open Microsoft.Xna.Framework
open Microsoft.Xna.Framework.Graphics

let WALL = -1
let EMPT = 0
let APPL = 1
let PLAYER = 2
let mazeMatrix =
    [| [| APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL|] 
       [| APPL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; APPL|] 
       [| APPL; APPL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; APPL; APPL|] 
       [| WALL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; WALL|] 
       [| APPL; APPL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; APPL; APPL|] 
       [| APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL|] 
       [| APPL; APPL; APPL; WALL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; WALL; APPL; APPL; APPL|] 
       [| WALL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; WALL|] 
       [| APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL|] 
       [| APPL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; WALL|] 
       [| APPL; APPL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; APPL; APPL|] 
       [| APPL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; WALL|] 
       [| APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL|] 
       [| WALL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; WALL|] 
       [| APPL; APPL; APPL; WALL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; WALL; APPL; APPL; APPL|] 
       [| APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL|] 
       [| APPL; APPL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; APPL; APPL|] 
       [| WALL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; APPL; WALL; WALL|] 
       [| APPL; APPL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; APPL; APPL|] 
       [| APPL; WALL; APPL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; WALL; WALL; WALL; WALL; APPL; WALL; APPL; WALL; APPL|] 
       [| APPL; APPL; APPL; WALL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; APPL; WALL; APPL; APPL; APPL|] 
       |]