module Maze

open Microsoft.Xna.Framework
open Microsoft.Xna.Framework.Graphics

let WALL = 1
let EMPT = 0
let mazeMatrix =
    [| [| EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT|] 
       [| EMPT; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; EMPT|] 
       [| EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT|] 
       [| WALL; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; WALL|] 
       [| EMPT; EMPT; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; EMPT; EMPT|] 
       [| EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT|] 
       [| EMPT; EMPT; EMPT; WALL; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; WALL; EMPT; EMPT; EMPT|] 
       [| WALL; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; WALL|] 
       [| EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT|] 
       [| EMPT; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; WALL|] 
       [| EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT|] 
       [| EMPT; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; WALL|] 
       [| EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT|] 
       [| WALL; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; WALL|] 
       [| EMPT; EMPT; EMPT; WALL; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; WALL; EMPT; EMPT; EMPT|] 
       [| EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT|] 
       [| EMPT; EMPT; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; EMPT; EMPT|] 
       [| WALL; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; EMPT; WALL; WALL|] 
       [| EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT|] 
       [| EMPT; WALL; EMPT; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; WALL; WALL; WALL; WALL; EMPT; WALL; EMPT; WALL; EMPT|] 
       [| EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; EMPT; WALL; EMPT; EMPT; EMPT|] 
       |]